name: Auto Merge Pull Request

on: workflow_dispatch

jobs:
  verifycode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v2

  mergecode:
    needs: verifycode
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Extract branch name
        id: extract_branch
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

      - name: Merge branch into main
        run: |
          git fetch origin ${{ steps.extract_branch.outputs.branch }}:${{ steps.extract_branch.outputs.branch }}
          git merge --no-ff --no-edit ${{ steps.extract_branch.outputs.branch }}
          git push origin main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
