name: Auto merge pullrequest

on: pull_request

jobs:
  get_pull_request_info:
    runs-on: ubuntu-latest
    
    steps:
      # Save variable data from pull request
      - name: Get Data From Pull Request
        env:
          PULL_REQUEST_CREATOR: ${{ github.event.pull_request.user.login }}
          PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
          PULL_REQUEST_BODY: ${{ github.event.pull_request.body }}
          PULL_REQUEST_TO_BRANCH: ${{ github.event.pull_request.base.ref }}
          PULL_REQUEST_FROM_BRANCH: ${{ github.event.pull_request.head.ref }}
          PULL_REQUEST_MERGABLE: ${{ github.event.pull_request.mergable }}
        
        run: echo "$PULL_REQUEST_FROM_MERGABLE"

  make_issue_to_merge:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    #Create an issue that the pullrequest is ready to be merged 
    steps:
      - name: Create Tickets
        run: |
          if [[ ${{ github.event.pull_request.mergeable }} == MergeableState.MERGEABLE ]]; then
            echo "IS ABLE TO MERGE"
          fi
            
          
