name: Auto merge pullrequest

on: pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Get Data From Pull Request
        env:
          PULL_REQUEST: ${{ github.event }}
        run: echo "$PULL_REQUEST.number"
      
      - name: Check Pullrequest
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
        
