name: Auto Merge Pullrequest
on:
  pull_request:
    branches:
      - '*'
    types: [opend]

jobs:
  verifycode:
    runs-on: ubuntu-latest
    env:
      BRANCH_TO_MERGE: ${{ github.event.inputs.branch_to }}
      
  mergecode:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checokout@v2
        with:
          ref: main
      - id: extract_branch
      - run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}" \
          git fetch origin ${{ steps.extract_branch.outputs.branch }}:${{ steps.extract_branch.outputs.branch }} \
          git merge --no-ff --no-edit ${{ steps.extract_branch.outputs.branch }} \
          git push origin main
