name: Auto merge pullrequest

on: pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Get Data From Pull Request
        env:
          PULL_REQUEST_CREATOR: ${{ github.event.pull_request}}
      
      - name: Check Pullrequest
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: | 
          "$GITHUB_CONTEXT.header"
          "$GITHUB_CONTEXT.body"
          "$GITHUB_CONTEXT.user.login"
        
        
