name: Auto merge pullrequest

on: pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: TEST_1
        run: echo "Test 1 works"
      
      - name: Check Pullrequest
        run: |
          echo TITLE: ${{ github.event.pull_request.title }} \
          echo BODY: ${{ github.event.pull_request.body }}
          echo WRITTEN BY: ${{ github.event.pull_request. }}
        
