name: Auto merge pullrequest

on:
  pull_request:
    types: [opened]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: TEST_1
        run: echo "Test 1 works"
      
      - name: Check Pullrequest
        run: echo ${{ github.event.pull_request.title }}
        
