name: Auto merge pullrequest

on: pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: TEST_1
        env:
          PULLREQUEST: ${{github.event.pullrequest}}
        run: $PULLREQUEST.id
      
      - name: Check Pullrequest
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
        
