name: Auto merge pullrequest

on: pull_request

jobs:
  get_pull_request_info:
    runs-on: ubuntu-latest
    steps:

      # Print data from pull request
      - name: Get Data From Pull Request
        env:
          PULL_REQUEST_CREATOR: ${{ github.event.pull_request.user.login }}
          PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
          PULL_REQUEST_BODY: ${{ github.event.pull_request.body }}
          PULL_REQUEST_TO_BRANCH: ${{ github.event.pull_request.base.ref }}
          PULL_REQUEST_FROM_BRANCH: ${{ github.event.pull_request.head.ref }}
          PULL_REQUEST_FROM_DIFF: ${{ git diff }}
        
        run: echo "test complete"
