name: push-pull-request-issue

on: [push]
jobs:
  read-and-print:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "commiter" ${{ github.actor }} && echo "message " ${{ github.event.commits[0].message }}
