name: push-pull-request-issue

on: [push]
permissions: write-all

jobs:
  read-and-print:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Commiter" ${{ github.actor }}
      - run: echo "Message " ${{ github.event.commits[0].message }}

  create-pull-request:
    needs: [read-and-print]
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4
      - run: gh pr create --title "New Pullrequest!" --body "this was made with github actions!"
      - run: gh issue create --title "this is a new issue!" --body "wow, pr is ready!" --label "question"
