name: Format Python Code
on: push
jobs:
  python-code-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.4"
          architecture: "x64"
      - name: Install packages
        run: pip install black autopep8 isort
      - name: Formatter
        run: |
          black .
          autopep8 --recursive --in-place --aggressive --aggressive .
          isort .

  run-unittests:
    needs: python-code-format
    runs-on: ubuntu-latest
    - steps:
      run: python experiment_unittest.py
