name: push-pull-request-issue

on: [push]
permissions: write

jobs:
  read-and-print:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Commiter" ${{ github.actor }}
      - run: echo "Message " ${{ github.event.commits[0].message }}

  create-pull-request:
    needs: [read-and-print]
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v2
      - run: gh pr create --title "New Pullrequest!" --body "this was made with github actions!"
